title: "Reading Blog"
author: "Iqbal Nurjadin"

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

repository: iqbalnurjadin/book-blog
