title: Text Bytes
author: Iqbal Nurjadin
email: textbyteswriters@gmail.com
description: >- # this means ignore new lines until "baseurl:"
  A blog by two friends writing about all things books; from reviewing new and classic books to discussing some of the important ways reading impacts our lives.
baseurl: ""
url: "textbytes.blog"
excerpt_separator: <!--more-->

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

repository: iqbalnurjadin/book-blog
