title: "Reading Blog"
author: "Iqbal Nurjadin"
url: "https://iqbalnurjadin.github.io/book-blog" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
